version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres-agent-test
    environment:
      POSTGRES_DB: odoo_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo_readonly"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
